/**
 * IPC wire protocol between core and a module worker.
 *
 * The forked module worker and the core-side broker talk ONLY over this typed, validated
 * envelope. Every inbound frame (in BOTH directions) is parsed with Zod before anything looks
 * at it — a malformed/hostile frame from the untrusted worker is dropped, never trusted. The
 * envelope is transport-agnostic: it travels over `child_process` IPC in production and over an
 * in-memory channel in unit tests (see {@link WorkerChannel}).
 *
 * This file defines ONLY the envelope (request / response correlation). The set of valid
 * methods + their param/result shapes is the BROKER's concern — keeping the
 * transport dumb and the security policy in one place.
 */
import { z } from 'zod';
import { RpcErrorCode } from '@sovecom/module-sdk';

// the stable {@link RpcErrorCode} vocabulary now lives in
// `@sovecom/module-sdk` (module authors may branch on it). Re-exported here so the in-tree
// runtime importers keep their `./ipc-protocol` import path.
export { RpcErrorCode };

/** Max serialized frame size we will accept from a worker (defence against memory abuse). */
export const MAX_FRAME_BYTES = 1 * 1024 * 1024; // 1 MiB

/** A correlation id linking a response to its request. Opaque, generated by the requester. */
export const correlationIdSchema = z.string().min(1).max(64);

/** A request frame: `method` is validated by the broker, not here. */
export const requestFrameSchema = z
  .object({
    kind: z.literal('req'),
    id: correlationIdSchema,
    method: z.string().min(1).max(128),
    params: z.unknown(),
  })
  .strict();

/** A response frame: success carries `result`, failure carries a structured `error`. */
export const responseFrameSchema = z
  .object({
    kind: z.literal('res'),
    id: correlationIdSchema,
    ok: z.boolean(),
    result: z.unknown().optional(),
    error: z
      .object({ code: z.string().max(64), message: z.string().max(2048) })
      .strict()
      .optional(),
  })
  .strict();

export const frameSchema = z.discriminatedUnion('kind', [requestFrameSchema, responseFrameSchema]);

export type RequestFrame = z.infer<typeof requestFrameSchema>;
export type ResponseFrame = z.infer<typeof responseFrameSchema>;
export type Frame = z.infer<typeof frameSchema>;

/**
 * A typed RPC failure. Carries a stable {@link RpcErrorCode} so the worker side can branch
 * (e.g. distinguish "forbidden" from "timeout") without string-matching.
 */
export class RpcError extends Error {
  constructor(
    readonly code: RpcErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'RpcError';
  }
}

/**
 * Parse an untrusted inbound value into a {@link Frame}, or return null if it is not a
 * well-formed frame. NEVER throws — a hostile worker must not be able to crash the parser by
 * sending garbage. Oversized payloads are rejected BEFORE Zod walks them.
 *
 * Over the production `child_process` fork (`serialization:'json'`) IPC frames arrive already
 * DESERIALIZED as objects — so a string-only size check would be dead code. We measure the
 * serialized byte size of the object too (guarded: a non-serializable/circular object fails
 * closed), bounding the memory a hostile worker can force core to hold per in-flight frame.
 */
export function parseFrame(raw: unknown): Frame | null {
  if (!withinSizeCap(raw)) return null;
  const result = frameSchema.safeParse(raw);
  return result.success ? result.data : null;
}

function withinSizeCap(raw: unknown): boolean {
  if (typeof raw === 'string') return Buffer.byteLength(raw, 'utf8') <= MAX_FRAME_BYTES;
  if (typeof raw === 'object' && raw !== null) {
    try {
      return Buffer.byteLength(JSON.stringify(raw), 'utf8') <= MAX_FRAME_BYTES;
    } catch {
      return false; // circular / non-serializable → reject (fail closed)
    }
  }
  return true; // primitives are tiny; Zod will reject non-frames anyway
}
